site_name: ukp0
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: ukp0
      handlers:
        python:
          options:
            docstring_style: numpy